/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as WatcherImport } from './routes/watcher'
import { Route as RegistriesImport } from './routes/registries'
import { Route as RecordsImport } from './routes/records'
import { Route as RecordDetailsImport } from './routes/record-details'
import { Route as RegistriesNamespaceidImport } from './routes/registries.$namespace_id'
import { Route as RecordsNamespaceidRegistrynameImport } from './routes/records.$namespace_id.$registry_name'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const WatcherRoute = WatcherImport.update({
  id: '/watcher',
  path: '/watcher',
  getParentRoute: () => rootRoute,
} as any)

const RegistriesRoute = RegistriesImport.update({
  id: '/registries',
  path: '/registries',
  getParentRoute: () => rootRoute,
} as any)

const RecordsRoute = RecordsImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => rootRoute,
} as any)

const RecordDetailsRoute = RecordDetailsImport.update({
  id: '/record-details',
  path: '/record-details',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const RegistriesNamespaceidRoute = RegistriesNamespaceidImport.update({
  id: '/$namespace_id',
  path: '/$namespace_id',
  getParentRoute: () => RegistriesRoute,
} as any)

const RecordsNamespaceidRegistrynameRoute =
  RecordsNamespaceidRegistrynameImport.update({
    id: '/$namespace_id/$registry_name',
    path: '/$namespace_id/$registry_name',
    getParentRoute: () => RecordsRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/record-details': {
      id: '/record-details'
      path: '/record-details'
      fullPath: '/record-details'
      preLoaderRoute: typeof RecordDetailsImport
      parentRoute: typeof rootRoute
    }
    '/records': {
      id: '/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof RecordsImport
      parentRoute: typeof rootRoute
    }
    '/registries': {
      id: '/registries'
      path: '/registries'
      fullPath: '/registries'
      preLoaderRoute: typeof RegistriesImport
      parentRoute: typeof rootRoute
    }
    '/watcher': {
      id: '/watcher'
      path: '/watcher'
      fullPath: '/watcher'
      preLoaderRoute: typeof WatcherImport
      parentRoute: typeof rootRoute
    }
    '/registries/$namespace_id': {
      id: '/registries/$namespace_id'
      path: '/$namespace_id'
      fullPath: '/registries/$namespace_id'
      preLoaderRoute: typeof RegistriesNamespaceidImport
      parentRoute: typeof RegistriesImport
    }
    '/records/$namespace_id/$registry_name': {
      id: '/records/$namespace_id/$registry_name'
      path: '/$namespace_id/$registry_name'
      fullPath: '/records/$namespace_id/$registry_name'
      preLoaderRoute: typeof RecordsNamespaceidRegistrynameImport
      parentRoute: typeof RecordsImport
    }
  }
}

// Create and export the route tree

interface RecordsRouteChildren {
  RecordsNamespaceidRegistrynameRoute: typeof RecordsNamespaceidRegistrynameRoute
}

const RecordsRouteChildren: RecordsRouteChildren = {
  RecordsNamespaceidRegistrynameRoute: RecordsNamespaceidRegistrynameRoute,
}

const RecordsRouteWithChildren =
  RecordsRoute._addFileChildren(RecordsRouteChildren)

interface RegistriesRouteChildren {
  RegistriesNamespaceidRoute: typeof RegistriesNamespaceidRoute
}

const RegistriesRouteChildren: RegistriesRouteChildren = {
  RegistriesNamespaceidRoute: RegistriesNamespaceidRoute,
}

const RegistriesRouteWithChildren = RegistriesRoute._addFileChildren(
  RegistriesRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/record-details': typeof RecordDetailsRoute
  '/records': typeof RecordsRouteWithChildren
  '/registries': typeof RegistriesRouteWithChildren
  '/watcher': typeof WatcherRoute
  '/registries/$namespace_id': typeof RegistriesNamespaceidRoute
  '/records/$namespace_id/$registry_name': typeof RecordsNamespaceidRegistrynameRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/record-details': typeof RecordDetailsRoute
  '/records': typeof RecordsRouteWithChildren
  '/registries': typeof RegistriesRouteWithChildren
  '/watcher': typeof WatcherRoute
  '/registries/$namespace_id': typeof RegistriesNamespaceidRoute
  '/records/$namespace_id/$registry_name': typeof RecordsNamespaceidRegistrynameRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/record-details': typeof RecordDetailsRoute
  '/records': typeof RecordsRouteWithChildren
  '/registries': typeof RegistriesRouteWithChildren
  '/watcher': typeof WatcherRoute
  '/registries/$namespace_id': typeof RegistriesNamespaceidRoute
  '/records/$namespace_id/$registry_name': typeof RecordsNamespaceidRegistrynameRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/record-details'
    | '/records'
    | '/registries'
    | '/watcher'
    | '/registries/$namespace_id'
    | '/records/$namespace_id/$registry_name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/record-details'
    | '/records'
    | '/registries'
    | '/watcher'
    | '/registries/$namespace_id'
    | '/records/$namespace_id/$registry_name'
  id:
    | '__root__'
    | '/'
    | '/record-details'
    | '/records'
    | '/registries'
    | '/watcher'
    | '/registries/$namespace_id'
    | '/records/$namespace_id/$registry_name'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  RecordDetailsRoute: typeof RecordDetailsRoute
  RecordsRoute: typeof RecordsRouteWithChildren
  RegistriesRoute: typeof RegistriesRouteWithChildren
  WatcherRoute: typeof WatcherRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  RecordDetailsRoute: RecordDetailsRoute,
  RecordsRoute: RecordsRouteWithChildren,
  RegistriesRoute: RegistriesRouteWithChildren,
  WatcherRoute: WatcherRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/record-details",
        "/records",
        "/registries",
        "/watcher"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/record-details": {
      "filePath": "record-details.tsx"
    },
    "/records": {
      "filePath": "records.tsx",
      "children": [
        "/records/$namespace_id/$registry_name"
      ]
    },
    "/registries": {
      "filePath": "registries.tsx",
      "children": [
        "/registries/$namespace_id"
      ]
    },
    "/watcher": {
      "filePath": "watcher.tsx"
    },
    "/registries/$namespace_id": {
      "filePath": "registries.$namespace_id.tsx",
      "parent": "/registries"
    },
    "/records/$namespace_id/$registry_name": {
      "filePath": "records.$namespace_id.$registry_name.tsx",
      "parent": "/records"
    }
  }
}
ROUTE_MANIFEST_END */
